name: hello
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^5.0.5
  google_fonts: ^6.0.0
  flutter_riverpod: ^1.0.4
  carousel_slider: ^4.2.1
  flutter_spinkit: ^5.2.0
  country_state_city_picker: ^1.2.8
  provider: ^6.0.5
  razorpay_flutter: ^1.3.5
  toast: ^0.3.0
  url_launcher: ^6.1.10
 
go_router:^5.0.5:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
